// frontend/src/components/EntryViewModal.jsx
import React from "react";
import { X, Paperclip } from "lucide-react";
import api from "../api/axios.js";

const formatCurrency = (value) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);

const apiOrigin = (api.defaults.baseURL || "")
  .replace(/\/api\/?$/, "")
  .replace(/\/$/, "");

const invoiceHref = (url) => {
  if (!url) return null;
  const token = localStorage.getItem("token") || "";
  const sep = url.includes("?") ? "&" : "?";
  const absolute = url.startsWith("http") ? url : `${apiOrigin}${url}`;
  return `${absolute}${sep}token=${encodeURIComponent(token)}`;
};

export default function EntryViewModal({ entry, type, onClose }) {
  if (!entry) return null;

  const renderField = (label, value) => (
    <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid #f0f0f0", padding: "6px 0", gap: 12 }}>
      <span style={{ fontWeight: 500, color: "#475569", flexShrink: 0 }}>{label}</span>
      <span style={{ textAlign: "right", wordBreak: "break-word" }}>{value ?? "—"}</span>
    </div>
  );

  let fields = [];
  let invoiceUrl = null;
  let invoiceName = null;

  if (type === "lab") {
    fields = [
      ["Date", entry.entry_date],
      ["Patient", entry.patient_name],
      ["Test", entry.test_name],
      ["Employee", entry.employee_name],
      ["Total Paid", formatCurrency(entry.total_amount_paid)],
      ["Referral By", entry.referral_by],
      ["Referral Amount", formatCurrency(entry.referral_amount)],
      ["Paid to Other Labs", formatCurrency(entry.paid_to_other_labs)],
      ["Remarks", entry.remarks],
    ];
  } else if (type === "expense") {
    fields = [
      ["Date", entry.expense_date],
      ["Category", entry.category],
      ["Amount", formatCurrency(entry.amount)],
      ["Remarks", entry.remarks],
    ];
  } else if (entry._type === "ledger" || entry.category === "Ledger") {
    // ✅ Ledger entries
    fields = [
      ["Date", entry.entry_date],
      ["Customer", entry.customer_name],
      ["Total Amount", formatCurrency(entry.total_amount || entry.amount)],
      ["Paid", formatCurrency(entry.paid)],
      ["Balance", formatCurrency(entry.balance)],
      ["Remarks", entry.remarks],
    ];
    invoiceUrl = entry.invoice_url;
    invoiceName = entry.invoice_original_name;
  } else {
    // Standard finance entry
    fields = [
      ["Date", entry.entry_date],
      ["Type", entry.entry_type],
      ["Category", entry.category],
      ["Sub-Category", entry.sub_category],
      ["Amount", formatCurrency(entry.amount)],
      ["Generated By", entry.generated_by],
      ["Revenue Type", entry.revenue_type],
      ["Patient Name", entry.patient_name],
      ["Patient Place", entry.patient_place],
      ["Client Name", entry.client_name],
      ["GST Number", entry.gst_number],
      ["GST Tax %", entry.gst_tax_percent],
      ["Tax Invoice No.", entry.tax_invoice_number],
      ["Remarks", entry.remarks],
    ];
    invoiceUrl = entry.invoice_url;
    invoiceName = entry.invoice_original_name || entry.invoice_filename;
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" style={{ maxWidth: 500 }} onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>Entry Details</h2>
          <button type="button" onClick={onClose} className="modal-close">
            <X size={20} />
          </button>
        </div>
        <div className="modal-body" style={{ padding: "16px 24px" }}>
          {fields.map(([label, value]) => renderField(label, value))}

          {invoiceUrl && (
            <div style={{ marginTop: 16, paddingTop: 12, borderTop: "1px solid #e2e8f0" }}>
              <div style={{ fontSize: 12, color: "#6b7280", marginBottom: 6 }}>Invoice / Attachment</div>
              <a
                href={invoiceHref(invoiceUrl)}
                target="_blank"
                rel="noreferrer"
                className="btn btn-secondary"
                style={{ display: "inline-flex", alignItems: "center", gap: 6 }}
              >
                <Paperclip size={15} /> {invoiceName || "View invoice"}
              </a>
            </div>
          )}
        </div>
        <div className="modal-footer">
          <button type="button" onClick={onClose} className="btn btn-secondary">Close</button>
        </div>
      </div>
    </div>
  );
}