import React from "react";
import toast from "react-hot-toast";
import { Pencil, Trash2, FileText, Eye } from "lucide-react";

import api from "../api/axios.js";

const formatCurrency = (value) => {
  const number = Number(value || 0);
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(number);
};

const getApiOrigin = () => {
  const base = api.defaults.baseURL || "";
  return base.replace(/\/api\/?$/, "").replace(/\/$/, "");
};

const handleViewInvoice = async (entry) => {
  try {
    if (!entry?.invoice_url) {
      toast.error("Invoice file not found.");
      return;
    }

    let fullUrl = entry.invoice_url;
    if (!fullUrl.startsWith("http://") && !fullUrl.startsWith("https://")) {
      const origin = getApiOrigin() || window.location.origin;
      fullUrl = `${origin}${fullUrl}`;
    }

    const response = await api.get(fullUrl, { responseType: "blob" });

    const contentType = response.headers["content-type"] || "application/pdf";
    const blob = new Blob([response.data], { type: contentType });
    const fileUrl = window.URL.createObjectURL(blob);

    const newWindow = window.open(fileUrl, "_blank");
    if (!newWindow) {
      toast.error("Please allow pop-ups to view the invoice.");
    }

    setTimeout(() => window.URL.revokeObjectURL(fileUrl), 60000);
  } catch (error) {
    console.error("Invoice open error:", error);
    const status = error.response?.status;
    if (status === 401) toast.error("Session expired. Please login again.");
    else if (status === 403) toast.error("You are not authorized to view this invoice.");
    else if (status === 404) toast.error("Invoice file not found.");
    else toast.error("Unable to open invoice.");
  }
};

export default function FinanceTable({
  entries = [],
  onEdit,
  onDelete,
  onView,
}) {
  if (!entries || entries.length === 0) {
    return (
      <div className="empty-state">
        No finance entries found for this filter. Click "Add Entry" to
        create one.
      </div>
    );
  }

  // ---- Column visibility: only render a column if at least one row has the field ----
  const showSubCategory       = entries.some((e) => e?.sub_category);
  const showClientName        = entries.some((e) => e?.client_name);
  const showGstNumber         = entries.some((e) => e?.gst_number);
  const showGstTax            = entries.some(
    (e) => e?.gst_tax_percent !== null && e?.gst_tax_percent !== undefined
  );
  const showTaxInvoiceNumber  = entries.some((e) => e?.tax_invoice_number);
  const showItems             = entries.some(
    (e) => Array.isArray(e?.items) && e.items.length > 0
  );
  const showPatientName       = entries.some((e) => e?.patient_name);
  const showPatientPlace      = entries.some((e) => e?.patient_place);
  const showGeneratedBy       = entries.some((e) => e?.generated_by);
  const showRevenueType       = entries.some((e) => e?.revenue_type);
  const showExecDepartment    = entries.some((e) => e?.exec_department);
  const showEmployeeName      = entries.some((e) => e?.employee_name);
  const showVehicleType       = entries.some((e) => e?.vehicle_type);          // ✅ NEW
  const showPurpose           = entries.some((e) => e?.purpose);               // ✅ NEW
  const showSalaryAmount      = entries.some(
    (e) => e?.salary_amount !== null && e?.salary_amount !== undefined
  );
  const showAllowanceAmount   = entries.some(
    (e) => e?.allowance_amount !== null && e?.allowance_amount !== undefined
  );
  const showTeam              = entries.some((e) => e?.team);
  const showLedgerDetails     = entries.some((e) => e._type === "ledger");
  const showInvoice           = entries.some((e) => e?.invoice_url);

  return (
    <div className="table-responsive">
      <table className="finance-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Category</th>
            {showSubCategory && <th>Sub-Category</th>}
            {showClientName && <th>Client Name</th>}
            {showGstNumber && <th>GST Number</th>}
            {showGstTax && <th className="text-right">GST Tax %</th>}
            {showTaxInvoiceNumber && <th>Tax Invoice #</th>}
            {showItems && <th>Items</th>}
            {showPatientName && <th>Patient Name</th>}
            {showPatientPlace && <th>Patient Place</th>}
            {showGeneratedBy && <th>Generated By</th>}
            {showRevenueType && <th>Revenue Type</th>}
            {showExecDepartment && <th>Exec Dept</th>}
            {showEmployeeName && <th>Employee</th>}
            {showVehicleType && <th>Vehicle Type</th>}              {/* ✅ NEW */}
            {showPurpose && <th>Purpose</th>}                        {/* ✅ NEW */}
            {showSalaryAmount && <th className="text-right">Salary</th>}
            {showAllowanceAmount && <th className="text-right">Allowance</th>}
            {showTeam && <th>Team</th>}
            <th className="text-right">Amount</th>
            {showLedgerDetails && <th>Customer / Details</th>}
            <th>Remarks</th>
            {showInvoice && <th>Invoice</th>}
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {entries.map((entry) => {
            const items = Array.isArray(entry.items) ? entry.items : [];
            const itemNames = items
              .map((item) => {
                const qty = Number(item.quantity || 0);
                return `${item.item_name || "Item"} (x${qty})`;
              })
              .join(", ");

            const isLedger = entry._type === "ledger";

            return (
              <tr key={entry.id}>
                <td style={{ whiteSpace: "nowrap" }}>
                  {entry.entry_date || "—"}
                </td>
                <td>
                  <span
                    className={`badge ${
                      entry.entry_type === "Income"
                        ? "badge-income"
                        : "badge-expense"
                    }`}
                  >
                    {entry.entry_type || "—"}
                  </span>
                </td>
                <td>{entry.category || "—"}</td>
                {showSubCategory && <td>{entry.sub_category || "—"}</td>}
                {showClientName && <td>{entry.client_name || "—"}</td>}
                {showGstNumber && <td>{entry.gst_number || "—"}</td>}
                {showGstTax && (
                  <td className="text-right">
                    {entry.gst_tax_percent !== null && entry.gst_tax_percent !== undefined
                      ? `${Number(entry.gst_tax_percent)}%`
                      : "—"}
                  </td>
                )}
                {showTaxInvoiceNumber && (
                  <td>{entry.tax_invoice_number || "—"}</td>
                )}
                {showItems && (
                  <td>
                    {items.length > 0
                      ? `${items.length} item${items.length > 1 ? "s" : ""} — ${itemNames}`
                      : "—"}
                  </td>
                )}
                {showPatientName && <td>{entry.patient_name || "—"}</td>}
                {showPatientPlace && <td>{entry.patient_place || "—"}</td>}
                {showGeneratedBy && <td>{entry.generated_by || "—"}</td>}
                {showRevenueType && <td>{entry.revenue_type || "—"}</td>}
                {showExecDepartment && <td>{entry.exec_department || "—"}</td>}
                {showEmployeeName && <td>{entry.employee_name || "—"}</td>}
                {showVehicleType && <td>{entry.vehicle_type || "—"}</td>}   {/* ✅ NEW */}
                {showPurpose && (
                  <td
                    style={{
                      maxWidth: 220,
                      whiteSpace: "normal",
                      wordBreak: "break-word",
                    }}
                    title={entry.purpose || ""}
                  >
                    {entry.purpose || "—"}
                  </td>
                )}                                                          {/* ✅ NEW */}
                {showSalaryAmount && (
                  <td className="text-right">
                    {formatCurrency(entry.salary_amount)}
                  </td>
                )}
                {showAllowanceAmount && (
                  <td className="text-right">
                    {formatCurrency(entry.allowance_amount)}
                  </td>
                )}
                {showTeam && <td>{entry.team || "—"}</td>}
                <td className="text-right" style={{ fontWeight: 600 }}>
                  {formatCurrency(entry.amount)}
                </td>
                {showLedgerDetails && (
                  <td>
                    {isLedger ? (
                      <div>
                        <div><strong>Customer:</strong> {entry.customer_name || "—"}</div>
                        <div><strong>Paid:</strong> {formatCurrency(entry.paid)}</div>
                        <div><strong>Balance:</strong> {formatCurrency(entry.balance)}</div>
                      </div>
                    ) : (
                      "—"
                    )}
                  </td>
                )}
                <td>{entry.remarks || "—"}</td>
                {showInvoice && (
                  <td>
                    {entry.invoice_url ? (
                      <button
                        type="button"
                        onClick={() => handleViewInvoice(entry)}
                        className="btn-icon"
                        title={entry.invoice_original_name || "View invoice"}
                      >
                        <FileText size={15} />
                      </button>
                    ) : (
                      "—"
                    )}
                  </td>
                )}
                <td>
                  <div className="actions-cell">
                    {onView && (
                      <button
                        type="button"
                        onClick={() => onView(entry)}
                        className="btn-icon"
                        title="View"
                      >
                        <Eye size={15} />
                      </button>
                    )}
                    {onEdit && (
                      <button
                        type="button"
                        onClick={() => onEdit(entry)}
                        className="btn-icon"
                        title="Edit"
                      >
                        <Pencil size={15} />
                      </button>
                    )}
                    {onDelete && (
                      <button
                        type="button"
                        onClick={() => onDelete(entry)}
                        className="btn-icon btn-icon--danger"
                        title="Delete"
                      >
                        <Trash2 size={15} />
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}