import React, { useEffect, useState, useCallback, useRef, useMemo } from "react";
import toast from "react-hot-toast";
import Navbar from "./Navbar.jsx";
import FilterBar from "./FilterBar.jsx";
import StatCards from "./StatCards.jsx";
import FinanceCharts from "./FinanceCharts.jsx";
import FinanceTable from "./FinanceTable.jsx";
import FinanceEntryForm from "./FinanceEntryForm.jsx";
import api from "../api/axios.js";

const PAGE_SIZE = 25;

const firstOfMonth = () => {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().split("T")[0];
};
const todayStr = () => new Date().toISOString().split("T")[0];

// Build a compact page-number array (with "…" ellipsis markers).
const buildPageNumbers = (current, total) => {
  if (total <= 7) return Array.from({ length: total }, (_, i) => i + 1);
  const pages = [];
  if (current <= 4) {
    for (let i = 1; i <= 5; i++) pages.push(i);
    pages.push("…", total);
  } else if (current >= total - 3) {
    pages.push(1, "…");
    for (let i = total - 4; i <= total; i++) pages.push(i);
  } else {
    pages.push(1, "…", current - 1, current, current + 1, "…", total);
  }
  return pages;
};

export default function FinanceDashboard({ department, title, roleColor }) {
  const apiBase = department.toLowerCase().replace(/\s/g, '');
  const supportsExcelImportExport = department === "PCM";

  const [startDate, setStartDate] = useState(firstOfMonth());
  const [endDate, setEndDate] = useState(todayStr());
  const [searchTerm, setSearchTerm] = useState("");

  const [entries, setEntries] = useState([]);
  const [summary, setSummary] = useState(null);
  const [options, setOptions] = useState(null);
  const [loading, setLoading] = useState(true);
  const [importing, setImporting] = useState(false);

  // NEW: pagination
  const [currentPage, setCurrentPage] = useState(1);

  const [formOpen, setFormOpen] = useState(false);
  const [editingEntry, setEditingEntry] = useState(null);

  const fileInputRef = useRef(null);

  const fetchOptions = useCallback(async () => {
    try {
      const res = await api.get(`/${apiBase}/options`);
      setOptions(res.data);
    } catch {
      toast.error("Failed to load form options.");
    }
  }, [apiBase]);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const params = { start_date: startDate, end_date: endDate };
      if (searchTerm) params.search = searchTerm;

      const [entriesRes, summaryRes] = await Promise.all([
        api.get(`/${apiBase}/entries`, { params }),
        api.get(`/${apiBase}/summary`, { params: { start_date: startDate, end_date: endDate } }),
      ]);
      setEntries(entriesRes.data.entries);
      setSummary(summaryRes.data);
    } catch (err) {
      toast.error("Failed to load finance data.");
    } finally {
      setLoading(false);
    }
  }, [apiBase, startDate, endDate, searchTerm]);

  useEffect(() => {
    fetchOptions();
  }, [fetchOptions]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  // NEW: reset page to 1 whenever any filter changes
  useEffect(() => {
    setCurrentPage(1);
  }, [startDate, endDate, searchTerm, department]);

  // NEW: paginated slice
  const totalEntries = entries.length;
  const totalPages = Math.max(1, Math.ceil(totalEntries / PAGE_SIZE));
  const safePage = Math.min(currentPage, totalPages);
  const pageNumbers = buildPageNumbers(safePage, totalPages);
  const rangeStart = totalEntries === 0 ? 0 : (safePage - 1) * PAGE_SIZE + 1;
  const rangeEnd = Math.min(safePage * PAGE_SIZE, totalEntries);

  const paginatedEntries = useMemo(
    () => entries.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE),
    [entries, safePage]
  );

  // Guard against out-of-range page when data shrinks
  useEffect(() => {
    if (currentPage > totalPages) setCurrentPage(totalPages);
  }, [currentPage, totalPages]);

  const handleReset = () => {
    setStartDate(firstOfMonth());
    setEndDate(todayStr());
    setSearchTerm("");
    setCurrentPage(1); // NEW
  };

  const handleDelete = async (entry) => {
    if (!window.confirm(`Delete this ${entry.entry_type.toLowerCase()} entry dated ${entry.entry_date}?`)) return;
    try {
      await api.delete(`/${apiBase}/entries/${entry.id}`);
      toast.success("Entry deleted.");
      fetchData();
    } catch {
      toast.error("Failed to delete entry.");
    }
  };

  const handleExportCsv = () => {
    if (!entries.length) {
      toast.error("No entries to export.");
      return;
    }
    const headers = ["Date", "Type", "Category", "Patient Name", "Patient Place", "Generated By", "Revenue Type", "Amount", "Remarks"];
    const rows = entries.map((e) => [
      e.entry_date, e.entry_type, e.category, e.patient_name || "", e.patient_place || "",
      e.generated_by || "", e.revenue_type || "", e.amount,
      (e.remarks || "").replace(/,/g, ";"),
    ]);
    const csv = [headers, ...rows].map((r) => r.join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${department}_Finance_${startDate}_to_${endDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportExcel = async () => {
    try {
      const res = await api.get(`/${apiBase}/export`, {
        params: { start_date: startDate, end_date: endDate },
        responseType: "blob",
      });
      const blob = new Blob([res.data], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${department}_Finance_${startDate}_to_${endDate}.xlsx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch {
      toast.error("Failed to export Excel file.");
    }
  };

  const handleExport = () => {
    if (supportsExcelImportExport) {
      handleExportExcel();
    } else {
      handleExportCsv();
    }
  };

  const handleImportClick = () => {
    fileInputRef.current?.click();
  };

  const handleImportFileChange = async (e) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;

    const formData = new FormData();
    formData.append("file", file);

    setImporting(true);
    try {
      const res = await api.post(`/${apiBase}/import`, formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      const { imported, errors } = res.data;
      if (imported > 0) {
        toast.success(`Imported ${imported} entr${imported === 1 ? "y" : "ies"}.`);
      }
      if (errors && errors.length) {
        toast.error(`${errors.length} row(s) skipped — check the sheet formatting.`);
      }
      fetchData();
    } catch (err) {
      const msg = err.response?.data?.message || "Failed to import the Excel file.";
      toast.error(msg);
    } finally {
      setImporting(false);
    }
  };

  const openNewEntry = () => {
    setEditingEntry(null);
    setFormOpen(true);
  };

  const openEditEntry = (entry) => {
    setEditingEntry(entry);
    setFormOpen(true);
  };

  return (
    <div className="page">
      <Navbar title={title} roleColor={roleColor} />

      <main className="page-main">
        <FilterBar
          startDate={startDate}
          endDate={endDate}
          onStartDateChange={setStartDate}
          onEndDateChange={setEndDate}
          onApply={fetchData}
          onReset={handleReset}
          onExport={handleExport}
          onAddNew={openNewEntry}
          searchTerm={searchTerm}
          onSearchChange={setSearchTerm}
        />

        {supportsExcelImportExport && (
          <div style={{ display: "flex", justifyContent: "flex-end", marginBottom: 12 }}>
            <input
              ref={fileInputRef}
              type="file"
              accept=".xlsx,.xlsm"
              style={{ display: "none" }}
              onChange={handleImportFileChange}
            />
            <button
              type="button"
              className="btn btn-secondary"
              onClick={handleImportClick}
              disabled={importing}
            >
              {importing ? "Importing..." : "Import Excel"}
            </button>
          </div>
        )}

        {summary && (
          <StatCards
            totalIncome={summary.total_income}
            totalExpenses={summary.total_expenses}
            profit={summary.profit}
            entryCount={summary.entry_count}
          />
        )}

        {summary && (
          <FinanceCharts trend={summary.trend} categoryBreakdown={summary.category_breakdown} />
        )}

        <div>
          <p className="section-title" style={{ marginBottom: 12 }}>Finance Entries</p>
          {loading ? (
            <div className="card empty-state">Loading...</div>
          ) : (
            <>
              <FinanceTable
                entries={paginatedEntries}
                onEdit={openEditEntry}
                onDelete={handleDelete}
              />

              {/* NEW: Pagination controls */}
              {totalEntries > 0 && (
                <div
                  className="card"
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    gap: 12,
                    flexWrap: "wrap",
                    marginTop: 12,
                  }}
                >
                  <span style={{ fontSize: 13, color: "#6b7280" }}>
                    Showing {rangeStart}–{rangeEnd} of {totalEntries} transactions
                  </span>

                  <div style={{ display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" }}>
                    <button
                      type="button"
                      className="btn btn-secondary"
                      disabled={safePage === 1}
                      onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                    >
                      Previous
                    </button>

                    {pageNumbers.map((p, idx) =>
                      p === "…" ? (
                        <span key={`ellipsis-${idx}`} style={{ padding: "0 6px", color: "#9ca3af" }}>
                          …
                        </span>
                      ) : (
                        <button
                          key={p}
                          type="button"
                          className={`btn ${p === safePage ? "btn-primary" : "btn-secondary"}`}
                          onClick={() => setCurrentPage(p)}
                          style={{ minWidth: 36 }}
                        >
                          {p}
                        </button>
                      )
                    )}

                    <button
                      type="button"
                      className="btn btn-secondary"
                      disabled={safePage === totalPages}
                      onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                    >
                      Next
                    </button>
                  </div>
                </div>
              )}
            </>
          )}
        </div>
      </main>

      <FinanceEntryForm
        open={formOpen}
        onClose={() => setFormOpen(false)}
        onSaved={fetchData}
        department={department}
        options={options}
        editingEntry={editingEntry}
      />
    </div>
  );
}